apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ecr-credentials-sa-users
subjects:
  - kind: Group
    name: system:serviceaccounts
    apiGroup: rbac.authorization.k8s.io
roleRef:
    kind: ClusterRole
    name: ecr-credentials-sa
    apiGroup: rbac.authorization.k8s.io